# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vidforge < Formula
  desc "Terminal-based universal video downloader"
  homepage "https://github.com/Abhi1264/vidforge"
  version "1.4.2"
  license "MIT"

  depends_on "ffmpeg"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Abhi1264/vidforge/releases/download/v1.4.2/vidforge_1.4.2_darwin_amd64.tar.gz"
      sha256 "9e9fb1019a98601c82c9f468c6612aafbcb1393692d2c5875dec6ea5e69018fe"

      def install
        bin.install "vidforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Abhi1264/vidforge/releases/download/v1.4.2/vidforge_1.4.2_darwin_arm64.tar.gz"
      sha256 "a15d5634c0cbda57e64cb4eda7fa55a5cb6bf4b967761539a1a1bf608ffe90ba"

      def install
        bin.install "vidforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abhi1264/vidforge/releases/download/v1.4.2/vidforge_1.4.2_linux_amd64.tar.gz"
      sha256 "6d7b5db4063bb8e9e831d0687ff1e12f2b43e0878fe2e65228a6b0d2730fcdca"
      def install
        bin.install "vidforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Abhi1264/vidforge/releases/download/v1.4.2/vidforge_1.4.2_linux_arm64.tar.gz"
      sha256 "e988c9c1256da6b432de47657ac86fba6c73a6490040020ff90ec363b15d94f9"
      def install
        bin.install "vidforge"
      end
    end
  end

  test do
    system "#{bin}/vidforge", "--version"
  end
end
